name: CI

on:
  push:
    branches:
     - main
    pull_request:
      branches:
      - main
     
jobs:
  build_and_test:
  
  env:
    BUILD_CONFIG: 'Release'
    SOLUTION: 'behaviourAPI.Core/BehaviourAPI.Core.sln'
    
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
      
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
      
    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true
      
